### PR TITLE
Refactor MTP split pathways

### LINKED ISSUE #1947: MTP speculative decoding + quantized KV cache (--kv-bits 8): AttributeError: 'tuple' object has no attribute 'shape' on qwen3_5 (v0.6.14)
## Summary

With `--kv-bits 8` (uniform scheme) + MTP speculative decoding (`--draft-kind mtp`), generation crashes at decode start with `AttributeError: 'tuple' object has no attribute 'shape'` on Qwen3.5-architecture models (e.g. Qwen3.8-27B). Short prompts sometimes slip through, but long-context requests (~13K+ prompt tokens) reproduce it reliably.

## Environment

- mlx-vlm 0.6.14 (pip), mlx 0.32.1
- macOS 27, Apple M2 Max 64GB, Python 3.13.5
- Model: `chimingw/Qwen3.8-27B-Uncensored-OrcaRouter-MLX-8bit` (qwen3_5 arch, `mtp_num_hidden_layers: 1`)
- Drafter: `mlx-community/Qwen3.8-27B-MTP-8bit`

## Reproduction

```bash
mlx_vlm.server \
  --model chimingw/Qwen3.8-27B-Uncensored-OrcaRouter-MLX-8bit \
  --kv-bits 8 \
  --draft-kind mtp --draft-model mlx-community/Qwen3.8-27B-MTP-8bit \
  --port 8080
```

Then POST `/v1/chat/completions` with a ~13-18K token prompt. Prefill completes; the first decode round crashes.

## Traceback

```
File ".../mlx_vlm/speculative/mtp.py", line 919, in _mtp_rounds_batch
  verify = _mtp_verify_target(...)
File ".../mlx_vlm/speculative/mtp.py", line 159, in _mtp_verify_target
  result = _mtp_verify_without_logits(lm, verify_input, prompt_cache)
File ".../mlx_vlm/speculative/mtp.py", line 64, in _mtp_verify_without_logits
  result = verify_hidden(verify_input, prompt_cache)
File ".../mlx_vlm/models/qwen3_5/language.py", line 2871, in speculative_verify_hidden
  out = self(inputs, ..., skip_logits=True)
File ".../mlx_vlm/models/qwen3_5/language.py", line 1641, in __call__
  prefix_len = keys.shape[-2] - L
               ^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'shape'
```

## Analysis

With KV cache quantization enabled, the prompt cache stores/returns quantized state as a tuple (e.g. `(keys, scales, zeros)` or similar), but the `speculative_verify_hidden` → attention path in `qwen3_5/language.py` treats `keys` as a plain array and calls `.shape` on it. The non-speculative path handles the quantized tuple correctly (normal generation with `--kv-bits 8` works fine without MTP), and MTP works fine without `--kv-bits` — only the combination crashes.

Possibly related to #1428 (TurboQuant KV + MTP), which was the same combination surfacing a different error.

## Workaround

Run MTP without `--kv-bits` (fp16 KV cache), or `--kv-bits 8` without MTP. Both configs work independently.

## Expected behavior

The MTP verify path should unpack quantized KV cache entries the same way the standard attention path does.

### PR DESCRIPTION
**Pull request by Lazarus-931**
Per https://github.com/Blaizzy/mlx-vlm/issues/1222

A unified way to do MTP wasn't present, it was broken from `mlx_vlm.convert` to `mlx_vlm/speculative/drafters/qwen3_5_mtp/split.py`, and across families there could have just been a more foundational structure to simplify it.

now with this cli: `mlx_vlm.split_mtp --model X --output Y [--model-type T]`, should be possible. it's also wired into `mlx_vlm.convert --mtp` so convert can emit the drafter in one go (opt-in, failure-isolated, quantizes to match the base).

migrated the 4 existing families onto a shared `MTPSplitter` base (byte-identical), added Qwen3-Next, and drafters can now be quantized. old per-model split CLIs still work. tests + README added.

Closes #1947

### CODE REVIEW

**Comment by lucasnewman** [comment]
@Lazarus-931 Looks good but there's a conflict that needs resolving.

File: .github/workflows/tests.yml [hunk 1]
```diff
@@ -34,6 +34,7 @@ jobs:
       - name: Install package and dependencies
         run: |
           python -m pip install pytest
+          python -m pip install sentencepiece
```
Comment (lucasnewman) [inline .github/workflows/tests.yml]: This shouldn't be necessary anymore, it's included in the requirements.

**Review by lucasnewman — APPROVED** [review]
LGTM
